version: "3.8"

services:
    backend:
        container_name: task-management-backend
        build: ./backend
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/var/www
        env_file:
            - backend/.env
        depends_on:
            - db

    frontend:
        container_name: task-management-frontend
        build: ./frontend
        ports:
            - "5173:5173"
        volumes:
            - ./frontend:/app
            - frontend_node_modules:/app/node_modules
        env_file:
            - frontend/.env
        depends_on:
            - backend

    db:
        container_name: task-management-db
        image: postgres:15
        environment:
            POSTGRES_DB: task_management
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret123
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
    frontend_node_modules:
